///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace GIT_SourceControl
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the GIT_SourceControlRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
    [RepositoryFolder("a1ef734e-b2bb-4065-a935-3729dcd97dc4")]
    public partial class GIT_SourceControlRepository : RepoGenBaseFolder
    {
        static GIT_SourceControlRepository instance = new GIT_SourceControlRepository();

        /// <summary>
        /// Gets the singleton class instance representing the GIT_SourceControlRepository element repository.
        /// </summary>
        [RepositoryFolder("a1ef734e-b2bb-4065-a935-3729dcd97dc4")]
        public static GIT_SourceControlRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public GIT_SourceControlRepository() 
            : base("GIT_SourceControlRepository", "/", null, 0, false, "a1ef734e-b2bb-4065-a935-3729dcd97dc4", ".\\RepositoryImages\\GIT_SourceControlRepositorya1ef734e.rximgres")
        {
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("a1ef734e-b2bb-4065-a935-3729dcd97dc4")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.1")]
    public partial class GIT_SourceControlRepositoryFolders
    {
    }
#pragma warning restore 0436
}